<a href="https://colab.research.google.com/github/Wildwolf4541/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to covere some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we are going to cover:
* Introduction to tensors.
* Getting info about tensors.
* Manipulating tensors.
* Tensors & Numpy.
* Using @tf.function (a way to speed up your regular python functions).
* Using GPUs with Tensorflow (or TPUs).
* Exercises to try.

# **Introduction to Tensors.**

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.19.0


## Tensor is an n-dimensional array of numbers where n can be 0(scalar), 1(vector), 2(matrix) upto infinity.

Creating Tensors-
* tf.constant() -> unchangeable
* tf.Variable() -> changeable using .assign
* random tensors
* shuffled tensors
* tf.ones and tf.zeros
* tf.constant(np.array,shape)-> Turn Numpy arrays into tensors

## Creating tensors with tf.constant()

In [2]:
scalar= tf.constant(7)
print(scalar)
# Check the number of dimenions of a tensor( ndim )
scalar.ndim

tf.Tensor(7, shape=(), dtype=int32)


0

In [3]:
# Create a vector
vector=tf.constant([10,10])
print(vector)

print(f"\n ndim= {vector.ndim}")

tf.Tensor([10 10], shape=(2,), dtype=int32)

 ndim= 1


In [4]:
# Create a matrix
matrix=tf.constant([[10,10],[10,20]])
print(matrix)

print(f"\n ndim= {matrix.ndim}")

tf.Tensor(
[[10 10]
 [10 20]], shape=(2, 2), dtype=int32)

 ndim= 2


In [5]:
# Create another matrix
matrix2=tf.constant([[10.,7.],[3.,2.],[1,5]],dtype=tf.float16)
print(matrix2)

print(f"\n ndim= {matrix2.ndim}") # number of dimensions or columns.

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 1.  5.]], shape=(3, 2), dtype=float16)

 ndim= 2


In [6]:
# Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                    [10,11,12]],
                   [[13,14,15],
                   [16,17,18]]])
print(tensor)
print(f"\n ndim= {tensor.ndim}")

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)

 ndim= 3


## Creating tensors with tf.Variable

In [7]:
changeable_tensor= tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating Random Tensors.
They are of arbitrary size with random numbers.

In [9]:
# Create two random but same tensors.
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility.
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in a tensor
valuable for when you want to shuffle your data so the inherent order doesn't affect the model learning.

In [10]:
not_shuffled=tf.constant([[10,7],
                          [1,2],
                          [3,4]])

# shuffling along the 1st dimension
tf.random.set_seed(42) # sets a global seed
tf.random.shuffle(not_shuffled,seed=42) # sets an operation-level seed

# Using both makes the shuffle fully reproducible

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

## ones and zeros

In [11]:
tf.ones(shape=[10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [12]:
tf.zeros([2,3],dtype= tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## Turn NumPy arrays into Tensorflow tensors.

In [13]:
import numpy as np
numpy_A= np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [14]:
a=tf.constant(numpy_A, shape=[3,2,4])
b=tf.constant(numpy_A)
a,b

(<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

-------------------------------------------------------------------------------
# **Getting Information from Tensors**
Attributes for information-
* Shape -> length of dimenisons of a tensor
* Rank -> number of tensor dimensions (scaler-0, vector-1, matrix-2)
* Axis or Dimension -> A particular dimension of a tensor
* Size -> Total number of items in the tensor

In [15]:
# Create a rank 4 tensor
r4_tensor = tf.zeros([2, 3, 4, 5])
r4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
r4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [17]:
print("Datatype of every element: ", r4_tensor.dtype)
print("Shape of tensor: ", r4_tensor.shape)
print("Rank of tensor: ", r4_tensor.ndim)
print("Total number of element in the tensor: ",tf.size(r4_tensor).numpy())
print("Elements along the 0 axis: ", r4_tensor.shape[0])

Datatype of every element:  <dtype: 'float32'>
Shape of tensor:  (2, 3, 4, 5)
Rank of tensor:  4
Total number of element in the tensor:  120
Elements along the 0 axis:  2


## Indexing Tensors
Tensors can be indexed just like Python lists.

In [18]:
list=tf.constant([1,2,3,4])
list[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [19]:
r4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Create a rank 2 tensor
r2_tensor=tf.constant([[1,2],[2,3]])
r2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [21]:
# Get last item of each row.
r2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

### Add in extra dimension to our r2_tensor

In [22]:
r3_tensor=r2_tensor[..., tf.newaxis]
r3_tensor

# or

r3_tensor=tf.expand_dims(r2_tensor,axis=-1)
r3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[2],
        [3]]], dtype=int32)>

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
# **Manipulating tensors (tensor operations)**

**Basic Operations** (tf.math.)
* tf.add  +
* tf.subtract  -
* tf.multiply  *
* tf.divide  /
* tf.square
* tf.sqrt
* tf.math.log

**Matrix Multiplication** (tf.linalg.matmul()) or use @ sumbol

**Reshaping Tensor** (tf.reshape(tensor,shape))

**Transpose** (tf.transpose())

**Dot Product** (tf.tensordot())

**CHange datatype** (tf.cast())

In [23]:
tensor= tf.constant([[1,2],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [24]:
tensor - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [25]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [26]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [27]:
tf.math.add(tensor,10)
tf.multiply(tensor,10)
tf.divide(tensor,10)
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [52]:
H=tf.range(1,10)
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [54]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [55]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Matrix Multiplication**

In [28]:
print(tensor)
# tf.linalg.matmul
tf.matmul(tensor,tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [29]:
# Lets have 2 tensors of shape 3,2 and 3,2 but we reshape the second.
X= tf.constant([[1,2],[3,4],[5,6]])
Y= tf.constant([[3,4],[5,6],[7,8]])

Y=tf.reshape(Y,shape=(2,3))
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 18, 21],
       [33, 40, 47],
       [51, 62, 73]], dtype=int32)>

In [30]:
X@Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 18, 21],
       [33, 40, 47],
       [51, 62, 73]], dtype=int32)>

**Transpose**

In [31]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

**Dot Product**

In [32]:
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 18, 21],
       [33, 40, 47],
       [51, 62, 73]], dtype=int32)>

In [33]:
## Changing the datatype of a tensor
B=tf.constant([1.7,2.3])
print(B)
print(B.dtype)

B1=tf.cast(B,dtype=tf.int32)
print(B1)
print(B1.dtype)

tf.Tensor([1.7 2.3], shape=(2,), dtype=float32)
<dtype: 'float32'>
tf.Tensor([1 2], shape=(2,), dtype=int32)
<dtype: 'int32'>


--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

-------------------------------------------------------------------------------
# **Tensorflow and NumPy**

## Aggregating Tensors
Condensing them from multiple values down to a smaller amount of values.

- Absolute of a tensor -> tf.abs(tensor)
- Minimum of a tensor -> tf.reduce_min(tensor)
- Maximum of a tensor -> tf.reduce_max(tensor)
- Mean of a tensor -> tf.reduce_mean(tensor)
- Sum of a tensor -> tf.reduce_sum(tensor)

import tensorflow_probability as tfp

- Variance of a tensor -> tf.math.reduce_variance(tensor) or tfp.stats.variance(tensor)
- Standard Deviation of a tensor -> tf.math.reduce_std(tensor)
- Mode of a tensor -> tfp.stats.mode(tensor)
- Median of a tensor -> tfp.stats.percentile(tensor, 50)


In [34]:
D=tf.constant([[-1,2],[-4,8]])
print(f"D= \n{D.numpy()}\n")
print(f"abs(D)= \n {tf.abs(D)}\n")
print(tf.reduce_min(D))
print(tf.reduce_max(D))
print(tf.reduce_mean(D))
print(tf.reduce_sum(D))

D_float = tf.cast(D, tf.float32)
print(tf.math.reduce_variance(D_float))
print(tf.math.reduce_std(D_float))

D= 
[[-1  2]
 [-4  8]]

abs(D)= 
 [[1 2]
 [4 8]]

tf.Tensor(-4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(19.6875, shape=(), dtype=float32)
tf.Tensor(4.43706, shape=(), dtype=float32)


In [35]:
# Create a random tensor with size of 50 elements and values between 0 and 100
E= tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15,  7, 51, 42, 16, 27, 21, 32, 15, 18, 95, 22, 35, 95, 31, 26, 68,
       46,  9,  2, 83, 82, 64, 81, 51, 56, 45, 90, 10, 35, 38, 19, 33, 61,
       74,  9,  3, 92, 44, 35, 76, 18, 65, 47, 31, 32, 21, 33,  1, 37])>

In [36]:
print(np.min(E), "and", tf.reduce_min(E).numpy())
print(np.max(E), "and", tf.reduce_max(E).numpy())
print(np.mean(E), "and", tf.reduce_mean(E).numpy())
print(np.sum(E), "and", tf.reduce_sum(E).numpy())

E_float=tf.cast(E,dtype=tf.float32)
print(np.var(E), "and", tf.math.reduce_variance(E_float).numpy())
print(np.std(E), "and", tf.math.reduce_std(E_float).numpy())


1 and 1
95 and 95
40.78 and 40
2039 and 2039
707.8116 and 707.81165
26.60472890296009 and 26.60473


In [37]:
import tensorflow_probability as tfp
print(tfp.stats.variance(E))
# print(tfp.stats.mode(E))
print(tfp.stats.percentile(E,50))

tf.Tensor(708, shape=(), dtype=int64)
tf.Tensor(35, shape=(), dtype=int64)


In [38]:
## Find the positional maximum and minimum.
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [39]:
tf.argmax(F), F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

### Squeezing a tensor (removing all single dimensions)

In [40]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [42]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
G.shape, G_squeezed.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

### One hot encoding

In [49]:
some_list=[0,1,2,3]

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [50]:
tf.one_hot(some_list,depth=4, on_value="yo", off_value="da")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo', b'da', b'da', b'da'],
       [b'da', b'yo', b'da', b'da'],
       [b'da', b'da', b'yo', b'da'],
       [b'da', b'da', b'da', b'yo']], dtype=object)>

In [57]:
# Create a tensor from numpy array
J=tf.constant(np.array([1,2,3,4]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [67]:
# Convert tensor to numpy array
np.array(J), type(J), type(np.array(J)), J.numpy()

(array([1, 2, 3, 4]),
 tensorflow.python.framework.ops.EagerTensor,
 numpy.ndarray,
 array([1, 2, 3, 4]))

# END
Go to colab notebook 01_neural_network_regression_with_tensorflow.ipynb